### ISSUE TITLE
Adres Alanı

### ISSUE THREAD

**Issue by emregeldegul** [selamet/online-yilbasi-cekilisi#1]
Malum pandemi dönemindeyiz ve herkes evlerinde (en azından olması gereken bu). Bu süreçte yan yana gelip hediyeleri vermektense adres bilgisi de alınıp mail ile göndermek güzel olmaz mı? Böylece hem "tam manası ile " sürpriz" olabilir hediyeyi alan kişiler için:) Ne dersiniz? İlgili Pr şimdi geliyor.

**Comment by selamet** [comment]
> Malum pandemi dönemindeyiz ve herkes evlerinde (en azından olması gereken bu). Bu süreçte yan yana gelip hediyeleri vermektense adres bilgisi de alınıp mail ile göndermek güzel olmaz mı? Böylece hem "tam manası ile " sürpriz" olabilir hediyeyi alan kişiler için:) Ne dersiniz? İlgili Pr şimdi geliyor.

Önerin için teşekkür ederiz. Bazı kullanıcılar adres kullanmak istemeyebilir. Bu yüzden front end de adres ekleme kısımını kullanıcıya bir seçenek olarak sunmanın daha iyi olacağını düşündük. Front end kısmını yazdıktan sonra pull request'inizi merge edeceğim.
