### ISSUE TITLE
Lisans bilgisi eksik

### ISSUE THREAD

**Issue by ooguz** [selamet/online-yilbasi-cekilisi#4]
Merhabalar,

Proje için bir lisans belirtilmemiş, AGPL v3+ lisansını öneriyorum. 

Lisansı önerme sebeplerimi daha önce şurada açıklamıştım, göz atabilirsiniz: [https://github.com/arguman/arguman.org/issues/383](https://github.com/arguman/arguman.org/issues/383)

Sevgiler,

**Comment by ilteriskeskin** [comment]
Merhabalar,

Lisans konusunu unuttuk hocam, ekliyoruz hemen :+1:  Öneriniz için teşekkür ederiz :) 

Sevgilerimizle.
